### Register an unknown user
Post http://localhost:3000/auth/register
Content-Type: application/json

{
  "username":"ethels",
  "password":"1234"
}
//OK the user is registered

### Register an already existing user
Post http://localhost:3000/auth/register
Content-Type: application/json

{
  "username":"ethels",
  "password":"1234"
}
//OK error 401 unauthorized

### Register with invalid username
Post http://localhost:3000/auth/register
Content-Type: application/json

{
  "username":"",
  "password":"1234"
}
// OK error bad request

### Register with invalid password
Post http://localhost:3000/auth/register
Content-Type: application/json

{
  "username":"ethels",
  "password":""
}
//OK error bad request

### Register with invalid data
Post http://localhost:3000/auth/register
Content-Type: application/json

{
  "username":"",
  "password":""
}
//OK error bad request

### Login an unknown user
POST http://localhost:3000/auth/login
Content-Type: application/json

{
  "username":"nobody",
  "password":"nobody"
}
//OK error 401 return, wich is right since the user dosn't exist in the detabase

### Login default user
POST http://localhost:3000/auth/login
Content-Type: application/json

{
  "username":"michele",
  "password":"michele"
}
//OK error 200 return OK

